### ISSUE TITLE
Finish 2.0 release notes

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-website#115]
The release notes for 2.0.0 need to be finished. Below is a link to the notes.

https://github.com/apache/accumulo-website/blob/master/_posts/release/2017-09-05-accumulo-2.0.0.md

Please comment on this issue with anything you think should be mentioned in the release notes.

**Comment by keith-turner** [comment]
Below is an incomplete list of information that could be added to the release notes.  This information was compiled from looking at commits, JIRA, GitHub Issues, and API diffs.  

 * Accumulo client ACCUMULO-4784
 * Removed deprecated method that used non API types.
 * Scan Executors ACCUMULO-4074 #555
 * Summaries  ACCUMULO-4500
 * Create table with splits and offline ACCUMULO-4808
 * New bulk import #436 #472
 * Caching ACCUMULO-4463 TinyLFU ACCUMULO-4177
 * Crypto updates
 * SPI package
 * Mutation and Key Fluent APIs ACCUMULO-4376 ACCUMULO-4746
 * Switch to Github Issues.
 * Hadoop 3 support  ACCUMULO-4826 #531
 * Docker support
 * New monitor ACCUMULO-4771
 * Java 8 ACCUMULO-4229
 * Better scripts (classpath) ACCUMULO-4490
 * accumulo testing repo
 * User manual reorg ACCUMULO-4630
 * ACCUMULO-4732 API for iter and loc groups for new table
 * impsort ACCUMULO-4682
 * Better memory configuration ACCUMULO-4612
 * Limit use of env ACCUMULO-4596
 * API cleanup ACCUMULO-4568
 * Examples moved to their own repo ACCUMULO-4511
 * Two tier compression ACCUMULO-1787
 * API definition now on website
 * Updated lots of deps
 * Less static state #613
 * Removed Mock #536
 * Support Zstandard compression #438
 * Grafana dashboard #404 ACCUMULO-4850
 * Internal code clean up : TableID .. metadata scanner… ServerCtx

**Comment by keith-turner** [comment]
I covered a lot of ground in 65a48e69a7644e5b6ab54ed732785a98f22907dd.   I still want to improve the release notes by linking to documentation more.

@milleruntime I looked into updating the link for crypto, but there were two crypto bullet points and I Was not sure what the best overall change was.  So I didn't make any change.

**Comment by ctubbsii** [comment]
I pushed up the 2.0.0-alpha-1 release notes, linking to the 2.0.0 draft ones. In case anybody had any thoughts on updating those also, it's there for modification.

**Comment by milleruntime** [comment]
> I looked into updating the link for crypto, but there were two crypto bullet points and I Was not sure what the best overall change was. So I didn't make any change.

Sorry I missed the second one.  They both are OBE and can be replaced by #560.

**Comment by ctubbsii** [comment]
Pretty sure this is done.
