### ISSUE TITLE
Update public API page for 2.0

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-website#154]
The following page needs to be updated for 2.0

https://accumulo.apache.org/api/

**Comment by jzgithub1** [comment]
I am trying to get EventMachine installed on my environment so I can get working on these issues.

**Comment by jzgithub1** [comment]
I am working on this now.

**Comment by jzgithub1** [comment]
We might want to do some mentions for the proxy in the future.

**Comment by ctubbsii** [comment]
Updated in the post-release tasks. If there's more to do, can open a new PR or issue.
