### ISSUE TITLE
Jquery from google will be slow in China

### ISSUE THREAD

**Issue by finchcn** [apache/accumulo-website#159]
In accumulo home page use jquery like this:
https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js
As well know google domain name will be very slow or blocked in China.

**Comment by mikewalch** [comment]
I updated the website (4c0f299ad5ade62dca6c0c6f) to use cdnjs/cloudflare.   I am going to close this issue but comment if you are still having trouble.

**Comment by finchcn** [comment]
@mikewalch Thanks for considering Chinese users
