### ISSUE TITLE
Improve release page

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-website#167]
https://accumulo.apache.org/contributor/making-release

There is a lot of good info on this page but it is a little hard to follow.  A nice TODO list at the top of the page, linking to each section would be great.  @ctubbsii [[VOTE] Apache Accumulo 1.9.3-rc3](http://apache-accumulo.1065345.n5.nabble.com/VOTE-Apache-Accumulo-1-9-3-rc3-tp23293p23317.html) email on the release vote made me think of this.

**Comment by keith-turner** [comment]
I didn't realize there was so much documentation about updating the website on that making-release page.  Would be good to link to that from the website readme.  I have updated the website readme in the past w/o realizing I may also need to update the making-release page.
