### ISSUE TITLE
Bad BasicCompactionStrategy link

### ISSUE THREAD

**Issue by elinaawise** [apache/accumulo-website#174]
BasicCompactionStrategy link in
https://accumulo.apache.org/docs/2.x/getting-started/table_configuration#compaction-strategies routes to error:

```xml
<Error>
   <Code>AccessDenied</Code>
   <Message>Access Denied</Message>
   <RequestId>5EC59568E1C3EE6F</RequestId>
   <HostId>ud1AeJXLawFywfoFx69lVhPQCdQp0omjPABSwgyzjtWl8lv+jwcUg0iGgxR/cRXVxtK9TcIG0dM=</HostId>
</Error>
```

**Comment by keith-turner** [comment]
This is because it only exist in an unreleased version of Accumulo.  The web page can only point to javadoc for released versions.  Once a release is made the contains BasicCompactionStrategy, the link should work.
