### ISSUE TITLE
Update new PMC members on people page

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo-website#190]
@hkeebler and @alerman were recently voted as committers/PMC members to Accumulo.

I'm creating this issue to encourage them to use their new privileges to commit directly to an Accumulo repository, and the easiest first commit is normally to each move themselves from the contributors section to the PMC section of the people page on the website.

**Comment by alerman** [comment]
I hadn't linked my github account to my Apache Id. That is done now so once that updates I will push the change for me. Thanks @ctubbsii

**Comment by ctubbsii** [comment]
@alerman Even without linking your Apache ID to your GitHub account, you can still push changes directly to: `https://gitbox.apache.org/repos/asf/accumulo{,-website, etc...}`

**Comment by alerman** [comment]
@ctubbsii Thanks! I was able to push up the changes for my information. I did not publish as there were changes after the build to my info and also to versions for accumulo2-maven-plugin I wasn't involved in.

**Comment by ctubbsii** [comment]
> @ctubbsii Thanks! I was able to push up the changes for my information. I did not publish as there were changes after the build to my info and also to versions for accumulo2-maven-plugin I wasn't involved in.

I don't see any changes other than yours. You may have an out-of-date asf-site branch.

Try something like the following to ensure your branch is up-to-date first before generating the site (assuming https://gitbox.apache.org/repos/asf/accumulo-website is `upstream`):
```bash
git remote update --prune
git checkout -t upstream/asf-site || git checkout asf-site
git reset --hard upstream/asf-site
git checkout -t upstream/master || git checkout master
git reset --hard upstream/master
_devtools/git-hooks/post-commit
git branch -vv
git push upstream : --dry-run
```
The output of `git branch -vv` should show that the asf-site branch is now one commit ahead of `upstream/asf-site`. Something like:
```
  asf-site f834951d [origin/asf-site: ahead 1] Jekyll build from master:813dfb1
* master   813dfb1f [origin/master] Fix ordering and update ATG link
```
You can verify the generated changes by doing:
```bash
git log -n1 -p asf-site
```

The output with the `--dry-run` should look similar to:
```
To https://gitbox.apache.org/repos/asf/accumulo-website
   06758ff3..f834951d  asf-site -> asf-site
```

The `asf-site` branch should be the only branch listed to be updated. If everything looks okay, then repeat the last command without `--dry-run` to actually push to the `asf-site` branch.

**Comment by ctubbsii** [comment]
@alerman It looks like you got a successful update of the website with 0db5af59556197483ca3302ed554f4c2af44fccd on the asf-site branch! Awesome!

**Comment by alerman** [comment]
@ctubbsii I sure did! Thanks for the help.

**Comment by hkeebler** [comment]
My update seemed to work.

**Comment by ctubbsii** [comment]
@hkeebler Your commit on the asf-site branch references: `build from master:86000a3`, but there is no commit on the master branch matching `86000a3`. I suspect you forgot to push the master branch along with the updated asf-site branch. Without the updates to the master branch, the generated updates in the asf-site branch will get clobbered when the next person builds.

**Comment by hkeebler** [comment]
So I also need to do a git push on the master?

**Comment by hkeebler** [comment]
Well I crashed and burned here.  I guess I won't be on the commit list very long.  @alerman did you push directly to the accumulo-website master?  I am unable to do that.

**Comment by alerman** [comment]
@hkeebler I did. I was able to after making sure my GitHub account was linked to my Apache id via https://gitbox.apache.org/setup/

**Comment by keith-turner** [comment]
> Well I crashed and burned here. I guess I won't be on the commit list very long. 

Its all good.  Can not learn w/o making mistakes. Much bigger mistakes have been made and will continue to be made.

**Comment by ctubbsii** [comment]
> So I also need to do a git push on the master? Well no I actually am not authorized to do that. I'm guessing I should have forked it. Will try that.

Yes, you have to push to master first (actually, I tend to push to master and to asf-site simultaneously with the `:` for the branch name, as indicated in my instructions above). You may not have permission to push to the GitHub repo unless you link your new Apache ID with your GitHub user name with the link Adam provided above. But, if you configure your remote to be `https://gitbox.apache.org/repos/asf/accumulo-website` instead of `https://github.com/apache/accumulo-website` (or similar GitHub ssh endpoint), you should have write access with your Apache ID credentials.

It looks like the most recent blog post update clobbered your changes to asf-site branch... but it's fine. If you can update your local repository, and re-apply your changes to master, and regenerate the asf-site, it shouldn't be a problem.

If you run into trouble, please don't hesitate to let us know where you're stuck.

**Comment by hkeebler** [comment]
I believe all is good now.  Thank you.  It seemed to take a while for the MFA status to complete.

**Comment by ctubbsii** [comment]
> I believe all is good now. Thank you. It seemed to take a while for the MFA status to complete.

Yep. Looks good!
