### ISSUE TITLE
Update S3 blog post to mention that bulk import may need S3Guard

### ISSUE THREAD

**Issue by keith-turner** [apache/accumulo-website#211]
Recently saw a talk by @joshelser about running Accumulo and HBase in AWS and Azure.  He mentioned that bulk import may need s3guard because the operation lists files.  Need to add this information to the blog post.  @joshelser do you have a link to your talk that I could add to the blog post?

**Comment by dlmarion** [comment]
According to [this](https://hadoop.apache.org/docs/r3.3.4/hadoop-aws/tools/hadoop-aws/s3guard.html#Overview), "Now that S3 is consistent, there is no need for S3Guard at all." Looks like it's been [removed](https://issues.apache.org/jira/browse/HADOOP-17409?jql=project%20%3D%20HADOOP%20AND%20text%20~%20S3Guard) in version 3.3.5.
