### ISSUE TITLE
Fix Tracing Documentation

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-website#269]
The 2.x documentation for Tracing has references to a class (specifically org.apache.accumulo.core.trace.DistributedTrace) that doesn't exist in 2.x anymore. See: 
https://accumulo.apache.org/docs/2.x/troubleshooting/tracing#instrumenting-a-client

**Comment by ctubbsii** [comment]
For background information, that non-API class was renamed to TraceUtil in apache/accumulo@426c93b83f16dbf638713d3b704f5a4a63f9c30e

**Comment by dlmarion** [comment]
I think this is OBE, tracing is done using OpenTelemetry in 2.1.0. Documentation updated in https://github.com/apache/accumulo-website/pull/304
