### ISSUE TITLE
Add troubleshooting steps on how to access restricted ZooKeeper values

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo-website#292]
Original Jira ticket: https://issues.apache.org/jira/browse/ACCUMULO-2469

The Jira ticket mentions the steps though I have not verified if that is still accurate or if it could be improved upon.

**Comment by EdColeman** [comment]
There is a ZooKeeper section in the manual at https://accumulo.apache.org/docs/2.x/troubleshooting/basic, it could go there.

The text from the original ticket is functionally correct.

```
Use zkCli.sh and look in /accumulo/<accumulo instance id>

Portions of ZooKeeper information is protected using ZooKeeper ACLs, to access protected data execute the following command:

> addauth digest accumulo:SECRET

Replace SECRET with the secret from your accumulo-site.xml file.
```

Also, the section that deals with using the ZooKeeper stat command will likely not work unless zookeeper four-letter words have been enabled, or a ZooKeeper admin server is configured - and that would have different methods for determining ZooKeeper state.

**Comment by EdColeman** [comment]
Another improvement in that section could be to document the ZooKeeper structure used by Accumulo - I through there used to be an open issue, but I can't find it quickly.  (Similar to the metadata structure section: https://accumulo.apache.org/docs/2.x/troubleshooting/system-metadata-tables)

**Comment by milleruntime** [comment]
:+1: * 1000
It wouldn't hurt to put it in multiple places.

**Comment by Manno15** [comment]
Thanks for the clarification and additional information @EdColeman.

**Comment by dlmarion** [comment]
@Manno15  - Does #338 resolve this?

**Comment by Manno15** [comment]
@dlmarion Yes, this appears to have been completed a long with a lot of useful information. Closing this issue.
