### ISSUE TITLE
Replace pluggable documentation with SPI

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-website#302]
With the next release, this section of the user manual needs to be updated accordingly: https://accumulo.apache.org/docs/2.x/getting-started/features#extensible-behaviors
The balancer is now part of the SPI and I think this would be a good place to describe the new SPI package. I think the 3 other sections can be removed.

**Comment by keith-turner** [comment]
There are package level javadocs for the SPI.  Would be good to link to those in the user manual.

**Comment by AlbertWhitlock** [comment]
Does PR #309 close this ticket?

**Comment by DomGarguilo** [comment]
> Does PR #309 close this ticket?

Looks like it was meant to close this ticket.

**Comment by DomGarguilo** [comment]
Closing as completed via #309
