### ISSUE TITLE
SPI javadoc is not included in 2.x Javadocs

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo-website#322]

**Comment by ctubbsii** [comment]
This was already addressed in apache/accumulo#1605
See https://github.com/apache/accumulo/blob/c44aca38bdb776a444410a5b0f97d31c2a46d105/pom.xml#L1600

**Comment by ctubbsii** [comment]
This will be updated when 2.1 is released and the javadocs are regenerated. We could regenerate them now, but it would differ from what is generated by the release tag for 2.0.1, so it could just get clobbered again if somebody regenerates them. So, I don't think there's anything to do here, but wait for 2.1 to include this change when building the javadocs for the site.
