### ISSUE TITLE
Update EOL Policy documentation

### ISSUE THREAD

**Issue by EdColeman** [apache/accumulo-website#340]
There is an [end of life project](https://endoflife.date/) that provides recommendations on documenting EOL policies [recommendations](https://endoflife.date/recommendations).

Accumulo has adopted a formal EOL policy and we may want to structure our documentation to adopt the conventions  suggested.

**Comment by EdColeman** [comment]
The site seemed to have a well written formal policy, that I believe that we are close to following - it seemed that we could use that information to refine our practices and even if we didn't formally adopt the whole thing, it could guide us if we wanted to go further along that route.

Basically it seemed to be good information and I wanted us to be aware of it as a community and see how far we wanted to go along with those recommendations.

**Comment by ctubbsii** [comment]
It's a good resource, but if there's nothing being proposed to *do* with it, then there's nothing to track as an issue, and this could have been an email to the dev list or mentioned in Slack. Are you proposing something specific be changed? If not... then I don't see the point of keeping this issue open.

**Comment by EdColeman** [comment]
I was proposing `we may want to structure our documentation to adopt the conventions suggested.`  That could be using the file naming convention, updating or adopting policy statements.... If I recall, there was a checklist - how many do we already comply with, how many are we close to if we just ..., which ones may not be something that we do not agree with or cannot adopt?  If someone went through that and presented it - that would be helpful.  Even if we do not have an EOL as they define it, using those conventions to make it clear that we don't, in a common form may be useful

I created it as an issue so that it would be visible to individuals that may want to contribute and maybe don't have a strong programming background.  While it is likely that some discussions may need to occur on one of our mail list to get consensus on any policy changes, as an issue it has a wider audience.  If this was only a discussion on our mailing list, outside individuals would certainly have a harder time finding it. As an issue it remains visible as a task that can be done by anyone that would like to pick this up and run with it. 

If no one expresses interest, we will evaluate if it is useful, or just close it. I think it is something that should be looked at and maybe I'll find time to look at it closer, until then (and hopefully) someone else will pick it up.

**Comment by ctubbsii** [comment]
> I was proposing `we may want to structure our documentation to adopt the conventions suggested.` That could be using the file naming convention, updating or adopting policy statements.... If I recall, there was a checklist - how many do we already comply with, how many are we close to if we just ..., which ones may not be something that we do not agree with or cannot adopt? If someone went through that and presented it - that would be helpful. Even if we do not have an EOL as they define it, using those conventions to make it clear that we don't, in a common form may be useful

I went through the checklist on their site, and we're already doing all the things that apply to us... which is why I was asking for a specific thing you think should be done. I don't see anything to do here that we're not already doing.

> 
> I created it as an issue so that it would be visible to individuals that may want to contribute and maybe don't have a strong programming background. While it is likely that some discussions may need to occur on one of our mail list to get consensus on any policy changes, as an issue it has a wider audience. If this was only a discussion on our mailing list, outside individuals would certainly have a harder time finding it. As an issue it remains visible as a task that can be done by anyone that would like to pick this up and run with it.

That's fine... but for tasks to be useful, they must be actionable for people to help out. I don't see anything actionable here. There's nothing to do as far as I can tell.

> 
> If no one expresses interest, we will evaluate if it is useful, or just close it. I think it is something that should be looked at and maybe I'll find time to look at it closer, until then (and hopefully) someone else will pick it up.

I've looked at it already... and evaluated it, and I don't think it's useful.

**Comment by EdColeman** [comment]
After @ctubbsii evaluated and nothing to do

**Comment by ctubbsii** [comment]
The one thing that we can do is put a specific date on the downloads page for the previous LTM release when we update it to add the next LTM release. I can add it to the release checklist.
