### ISSUE TITLE
Broken links on Making a Release page

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo-website#349]
Specifically, number 3 in [Setup](https://accumulo.apache.org/contributor/making-release#setup)

**Comment by ctubbsii** [comment]
That's very weird, because the Markdown looks okay, and there's nothing special about those links... they do work.

**Comment by ctubbsii** [comment]
Looks like this one was caused by some raw `<` and `>` reserved HTML5 chars inline prior to the link, which broke the markdown processing for the rest of the line.
