### ISSUE TITLE
Add svn instructions to Making a Release web page

### ISSUE THREAD

**Issue by dlmarion** [apache/accumulo-website#350]
The instructions say to upload the artifacts to a SVN repo [here](https://accumulo.apache.org/contributor/making-release#copy-artifacts-to-distapacheorg). Having not used svn in over a decade, it would be very useful to have example CLI instructions.

**Comment by dlmarion** [comment]
I was able to update the KEYS file by doing the following:

```
sudo yum install -y git-svn
git svn clone https://dist.apache.org/repos/dist/release/accumulo accumulo-dist-gitsvn
>> make changes to KEYS file
git add KEYS
git commit
git svn dcommit --username=<ASF_Username>
```

**Comment by ctubbsii** [comment]
There are many different `svn` clients out there, with lots of different instructions. To avoid scope creep, we should keep it very minimal. I think what you have is okay, but will only work in a specific environment. Even modern RPM-based distros have replaced `yum` with `dnf`. I'm going to see if I can find something more succinct to propose. I'll comment on your PR.

**Comment by dlmarion** [comment]
As to how git-svn is installed, I have no opinion. But, I would think that most of us developers would understand these instructions better than using a svn client directly. These instructions are for us developers, and most, if not all of us are using git (not svn).
