### ISSUE TITLE
Provide space on "people" page for Emeritus PMC members

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo-website#379]
At least one person on our PMC is now Emeritus (for that role, but remains a committer). The "people" page needs to be updated to be able to mark such individuals as Emeritus. Right now, it lists all PMC and committers in one big list. There are probably several different design options. Maybe using datatables could work to organize the list of contributors/committers/PMC members/Emeritus PMC members? Or just a separate "Committers / Emeritus PMC Members" section.

If anybody is interested in doing this, they could also suggest a similarly styled update over on the Fluo project for https://github.com/apache/fluo-website/issues/216

**Comment by keith-turner** [comment]
> Or just a separate "Committers / Emeritus PMC Members" section.

I like that option the best.  I gave it a try in #380.
