### ISSUE TITLE
Update javascript and css resources

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo-website#394]
Several libraries we use for the website are a bit out of date and could be updated. Here's a list of some:

* [ ] Bootstrap (currently using 3.3.7)
* [x] Font Awesome (currently using 4.0.3)
* [x] DataTables (currently using 1.10.12 based on jQuery 2.2.3)
* [x] jQuery (currently using 2.2.4)

Edit:
The above dependencies are all imported in default.html. The search page imports its own dependencies that need updating:

- [x] lunr
- [x] jquery

**Comment by ctubbsii** [comment]
Font Awesome, DataTables, and jQuery were updated in #396

**Comment by DomGarguilo** [comment]
lunr was updated in #399 and jquery import was removed from that page so the main import of jquery would be used.
