### ISSUE TITLE
Assess network port table in 2.x docs

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-website#402]
The table here: https://accumulo.apache.org/docs/2.x/administration/in-depth-install#network

Many of the entries in the table are deprecated or have broken links. It should be determined whether any should be removed or fixed.

![image](https://github.com/apache/accumulo-website/assets/47725857/710f549f-4e9a-4249-8480-9034026edf94)

**Comment by EdColeman** [comment]
It may not be needed for this issue - but it may help if any changes considered what may be necessary to address changes coming down the line with elasticity changes, things like multiple-managers,... 

One possibility would be a future change that wanted two columns for IP addresses, one 2.x, 3.x and a second for 4.0 that would map the changes necessary between versions?  Mainly just speculating that there will be significant changes and that could possibly made easier by planning ahead.  Or not...

**Comment by AlbertWhitlock** [comment]
Aren't some users not even on 2.1 yet? If that is true I think leaving the deprecated entries in makes sense (since that is when the replication code got deprecated.  These users will be looking for the 2.x docs). But there is at least one broken link here, monitor.port.log4j.

**Comment by AlbertWhitlock** [comment]
Dom.....I can take this one.

**Comment by ctubbsii** [comment]
I think all these were fixed by #409 . Can create a new issue or PR if there's more to do here.
