### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by DomGarguilo** [apache/accumulo-website#403]
There are some broken links in the docs that need updating/fixing. I briefly looked through some of the pages and there are probably others but here are a few that I found:

* The log4j links probably need to be updated to lo4j2 in this section: https://accumulo.apache.org/docs/2.x/administration/in-depth-install#configuration
* Looks like the manager and tserver link needs to be corrected in this sections: https://accumulo.apache.org/docs/2.x/administration/in-depth-install#cluster-specification
* The Zookeeper acls link in this section: https://accumulo.apache.org/docs/2.x/administration/upgrading#upgrading-from-110-or-20-to-21

**Comment by AlbertWhitlock** [comment]
Dom.....I can take this one.

**Comment by rsingh433** [comment]
I will take on this one.
