### ISSUE TITLE
Add search to documentation

### ISSUE THREAD

**Issue by mikewalch** [apache/accumulo-website#70]
It would be great to have a way to easily search the Accumulo 2.0+ documentation.

**Comment by ctubbsii** [comment]
This is hard with a static site... unless during generation, we index it and throw the index into something which we can process with Javascript.

Or, we can just put a Google custom search box on the page. https://cse.google.com/cse/

**Comment by mikewalch** [comment]
There are some search solutions for Jekyll that use javascript. Below are a few:

https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/
https://github.com/mathaywarduk/jekyll-search

Not sure how great these are but def worth checking out.  A custom search box might be good too.

**Comment by mikewalch** [comment]
Fixed by #81
